export const projects = [
  {
    title: "All Eat.",
    description:
      "All Eat, a mobile application designed and developed to address the gap in food delivery apps, the need for a more accessible way to order food for people with food allergies and dietary needs. Through comprehensive interviews with stakeholders including those with allergies and those without, the project aimed at being inclusive for everyone while still having a simple and easy to use interface. \n\nThe app uses a profile based system where each user on the app has their own diets and allergies selected and filters out unsafe dishes and removes recommendations which do not fit with the needs. It also features allergy-aware ordering, guest-friendly profiles, live delivery tracking, and post-meal feedback integration, all aimed at creating a safer and intuitive food delivery experience\n\nFollowing an agile development methodology, allowed for iterative testing and stakeholder to check the product in development to ensure that it still kept with their needs. The project makes use of a 3NF relational database, capturing ingredients for each dish, tags, diets and recommendation meta data including cuisines, and restaurant locations - combined, it allows for more personalised recommendations. Developed in Dart with a Flutter front-end and supported with PHP/MySQL on the backend  allowed for seamless integration with the cloud, facilitating syncing in real-time. The final product not only streamlines the ordering process but also a new standard for recommendations",
    url: "alleat",
    startDate: "2022-03",
    endDate: "2023-03",
    classification: ["A-Level Project"],
    type: "App Development",
    languages: ["Dart", "Flutter", "MySQL", "PHP"],
    tools: ["Adobe Illustrator", "Figma", "Visual Studio Code"],
    thumbnailImage: "/image/projects/alleat/slides/alleathomepageslide.webp",
    coverImage: "/image/projects/alleat/alleathomepage.png",
    imageGallery: [
      "/image/projects/alleat/slides/alleatcategoriesslide.webp",
      "/image/projects/alleat/slides/alleatconfirmedorderslide.webp",
      "/image/projects/alleat/slides/alleathomepageslide.webp",
      "/image/projects/alleat/slides/alleatitemslide.webp",
    ],
  },
  {
    title: "Kat Sullivan",
    description:
      "Kat Sullivan's blog website was developed from the ground up to be accessible for her to manage her content and constantly update it with any changes she needed to make - to facilitate this, I made use of WordPress which has a simple to use block based page building system. To design the site, I heavily used Figma in order to display mockups and get real-time feedback on how the site felt and places that they felt needed changing. Through iterations, it was found that some of the needs would not be able to be fully met by WordPress so PHP was used for some custom contact forms and subscription forms to different newsletters.",
    url: "katsullivan",
    startDate: "2020-03",
    endDate: "2020-05",
    languages: ["PHP"],
    classification: ["Work Project"],
    type: "Web Development",
    tools: ["WordPress", "Figma"],
    thumbnailImage:
      "/image/projects/katsullivan/slides/katsullivanhomepageslide.webp",
    coverImage: "/image/projects/katsullivan/katsullivanhomepage.png",
    imageGallery: [
      "/image/projects/katsullivan/slides/katsullivanaboutslide.webp",
      "/image/projects/katsullivan/slides/katsullivanblogslide.webp",
    ],
  },
  {
    title: "Passagetopoise",
    description: "",
    url: "passagetopoise",
    startDate: "2019-11",
    endDate: "2020-12",
    classification: ["Work Project"],
    type: "Web Development",
    languages: ["PHP"],
    tools: ["WordPress", "Figma"],
    thumbnailImage:
      "/image/projects/passagetopoise/slides/passagetopoisehomepageslide.webp",
    coverImage: "/image/projects/passagetopoise/passagetopoisehomepage.png",
    imageGallery: [
      "/image/projects/passagetopoise/slides/passagetopoiseblogslide.webp",
      "/image/projects/passagetopoise/slides/passagetopoisedescriptionslide.webp",
      "/image/projects/passagetopoise/slides/passagetopoiseshopslide.webp",
    ],
  },
  {
    title: "CPUR",
    description: "",
    url: "cpur",
    startDate: "2019-03",
    endDate: "2022-12",
    classification: ["Work Project"],
    type: "Web Development",
    languages: ["PHP"],
    tools: ["WordPress", "Figma", "Adobe Photoshop", "Adobe Illustrator"],
    thumbnailImage: "/image/projects/cpur/slides/cpurhomepageslide.webp",
    coverImage: "/image/projects/cpur/cpurhomepage.png",
    imageGallery: [
      "/image/projects/cpur/slides/cpurdatarecoveryslide.webp",
      "/image/projects/cpur/slides/cpurgetstartedslide.webp",
      "/image/projects/cpur/slides/cpurhomepageslide.webp",
      "/image/projects/cpur/slides/cpurrepairslide.webp",
    ],
  },
  {
    title: "SSH Cart",
    description: "",
    url: "sshcart",
    startDate: "2024-11-18",
    endDate: "2024-12-11",
    classification: ["University Project"],
    type: "Web Development",
    languages: ["HTML", "CSS", "JavaScript", "NodeJS"],
    tools: ["Visual Studio Code", "Docker", "MongoDB", "Figma"],
    coverImage: "/image/projects/sshcart/sshcart.png",
    thumbnailImage: "/image/projects/sshcart/slides/sshcartslide.webp",
    imageGallery: ["/image/placeholder.jpg"],
  },
  {
    title: "BlocDoc",
    description:
      "BlocDoc is a note-taking and study tool web application developed to enhance the student learning experience through integrated revision workflows. The project was created as part of the 2nd Year Team Project module run by the University of Birmingham and was made up of groups of 6-8 students working in an agile environment using vertical slicing and CI/CD practices.\n\nUnlike much of the other competition, it embeds the flashcards within documents, by making documents work through modular blocks, allowing for seamless transitions between reviewing cards and documents. The application contains a study page which compiles the flashcards from the documents and uses spaced repetition, encouraging long-term memory retention. Each document and flashcard, blocks can be inserted including text, tables, code, images and PDFs. Users can also export their documents into a variety formats or share them publicly.\n\nBlocDoc also includes an intelligent deadlines module to track assignments and assessments to allow users to manage their workload with colour-coded levels of priority - After a deadline is marked completed, it is placed in an archived table.",
    url: "blocdoc",
    startDate: "2025-01-19",
    endDate: "2025-05-04",
    coverImage: "/image/projects/blocdoc/blocdocdocument.png",
    thumbnailImage: "/image/projects/blocdoc/slides/blocdocdocumentslide.webp",
    classification: ["University Project"],
    type: "Web Development",
    languages: ["TypeScript", "CSS", "Java"],
    tools: ["JHipster", "Docker", "Figma", "Visual Studio Code"],
    imageGallery: ["/image/placeholder.jpg"],
  },
  {
    title: "Advanced News Classifier",
    description: "",
    url: "newsclassifier",
    startDate: "2023-11-27",
    endDate: "2023-12-11",
    classification: ["University Project"],
    type: "Machine Learning Development",
    languages: ["Java"],
    tools: ["IntelliJ IDEA"],
    thumbnailImage:
      "/image/projects/newsclassifier/slides/newsclassifierslide.webp",
    coverImage: "/image/projects/newsclassifier/newsclassifier.png",
    imageGallery: [""],
  },
  {
    title: "Record Shop",
    description: "",
    url: "recordshop",
    startDate: "2024-03-14",
    endDate: "2024-05-02",
    tags: [
      "Small Project",
      "University Project",
      "Backend Development",
      "Database Development",
    ],
    languages: ["Java", "JavaFX", "PostgreSQL"],
    tools: ["IntelliJ IDEA"],
    thumbnailImage: "/image/projects/recordshop/slides/recordshopslide.webp",
    coverImage: "/image/projects/recordshop/recordshop.png",
    imageGallery: [""],
  },
  {
    title: "30 Days of UI",
    description: "",
    url: "30daysofui",
    startDate: "2025-08",
    endDate: "2025-09",
    classification: ["Personal Project", "Challenge"],
    languages: [],
    type: "UI/UX Design",
    tools: ["Figma", "Adobe Photoshop", "Adobe Illustrator"],
    thumbnailImage: "image/projects/30daysofui/slides/30daysofuislide.webp",
    coverImage: "/image/projects/30daysofui/30daysofui.png",
    imageGallery: ["/image/placeholder.jpg"],
  },
];
