// title: "",
// description: "",
// url: "",
// startDate: "",
// endDate: "",
// tags: [],
// tools: [],
// coverImage: "",
// imageGallery: "",

export const projects = [
  {
    title: "All Eat.",
    description: "",
    url: "/alleat",
    startDate: "2022-03-01",
    endDate: "2023-03-01",
    tags: [
      "Large Project",
      "A-Level Project",
      "UI Design",
      "UX Design",
      "Mobile Development",
      "App Development",
    ],
    tools: ["Dart", "Flutter", "Figma"],
    coverImage: "/image/projects/alleat/slides/alleathomepageslide.webp",
  },
  {
    title: "Kat Sullivan",
    description: "",
    url: "",
    startDate: "2020-03-01",
    endDate: "2020-05-01",
    tags: ["Work Project", "Web Development", "UI Design", "UX Design"],
    tools: ["WordPress", "Figma", "PHP"],
    coverImage:
      "/image/projects/katsullivan/slides/katsullivanhomepageslide.webp",
  },
  {
    title: "Passagetopoise",
    description: "",
    url: "",
    startDate: "2019-11-01",
    endDate: "2020-12-01",
    tags: [
      "Work Project",
      "Web Development",
      "UI Design",
      "UX Design",
      "E-commerce",
    ],
    tools: ["WordPress", "Figma", "PHP"],
    coverImage:
      "/image/projects/passagetopoise/slides/passagetopoisehomepageslide.webp",
  },
  {
    title: "CPUR",
    description: "",
    url: "",
    startDate: "2019-03-01",
    endDate: "2022-12-01",
    tags: [
      "Work Project",
      "Web Development",
      "UI Design",
      "UX Design",
      "E-commerce",
    ],
    tools: ["WordPress", "Figma", "PHP"],
    coverImage: "/image/projects/cpur/slides/cpurhomepageslide.webp",
  },
  {
    title: "SSH Cart",
    description: "",
    url: "/sshcart",
    startDate: "2024-11-18",
    endDate: "2024-12-11",
    tags: [
      "Web Development",
      "University Project",
      "Frontend Development",
      "Web-app",
      "UI Design",
      "UX Design",
      "Medium Project",
    ],
    tools: [
      "Docker",
      "JavaScript",
      "HTML",
      "CSS",
      "MongoDB",
      "Node.js",
      "Figma",
    ],
    coverImage: "/image/placeholder.jpg",
  },
  {
    title: "BlocDoc",
    description: "",
    url: "/blocdoc",
    startDate: "2025-01-19",
    endDate: "2025-05-04",
    tags: [
      "Large Project",
      "University Project",
      "Web Development",
      "Full Stack Development",
      "Web-app",
      "UI Design",
      "UX Design",
    ],
    tools: ["JHipster", "TypeScript", "Docker", "CSS", "Java", "Figma"],
    coverImage: "/image/placeholder.jpg",
  },
  {
    title: "Advanced News Classifier",
    description: "",
    url: "",
    startDate: "2023-11-27",
    endDate: "2023-12-11",
    tags: [
      "Small Project",
      "University Project",
      "Natural Language Processing",
    ],
    tools: ["Java"],
    coverImage: "/image/placeholder.jpg",
  },
  {
    title: "Records Shop",
    description: "",
    url: "",
    startDate: "2024-03-14",
    endDate: "2024-05-02",
    tags: [
      "Small Project",
      "University Project",
      "Backend Development",
      "Database Development",
    ],
    tools: ["Java", "JavaFX", "PostgreSQL"],
    coverImage: "/image/placeholder.jpg",
  },
  {
    title: "30 Days of UI",
    description: "",
    url: "",
    startDate: "2025-08-01",
    endDate: "2025-09-01",
    tags: ["UI Design", "Challenge", "Personal Project"],
    tools: ["Figma", "Adobe Photoshop", "Adobe Illustrator"],
    coverImage: "image/projects/30daysofui/slides/30daysofuislide.webp",
  },
];
