export const projects = [
  {
    title: "All Eat.",
    description:
      "All Eat, a mobile application designed and developed to address the gap in food delivery apps, the need for a more accessible way to order food for people with food allergies and dietary needs. Through comprehensive interviews with stakeholders including those with allergies and those without, the project aimed at being inclusive for everyone while still having a simple and easy to use interface. \n\nThe app uses a profile based system where each user on the app has their own diets and allergies selected and filters out unsafe dishes and removes recommendations which do not fit with the needs. It also features allergy-aware ordering, guest-friendly profiles, live delivery tracking, and post-meal feedback integration, all aimed at creating a safer and intuitive food delivery experience\n\nFollowing an agile development methodology, allowed for iterative testing and stakeholder to check the product in development to ensure that it still kept with their needs. The project makes use of a 3NF relational database, capturing ingredients for each dish, tags, diets and recommendation meta data including cuisines, and restaurant locations - combined, it allows for more personalised recommendations. Developed in Dart with a Flutter front-end and supported with PHP/MySQL on the backend  allowed for seamless integration with the cloud, facilitating syncing in real-time. The final product not only streamlines the ordering process but also a new standard for recommendations",
    url: "alleat",
    startDate: "2022-03",
    endDate: "2023-03",
    featured: true,
    classification: ["A-Level Project"],
    type: "App Development",
    languages: ["Dart", "Flutter", "MySQL", "PHP"],
    tools: [
      "Adobe Illustrator",
      "Figma",
      "Visual Studio Code",
      "Android Studio",
    ],
    thumbnailImage: "/image/projects/alleat/slides/alleathomepageslide.webp",
    coverImage: "/image/projects/alleat/alleathomepage.png",
    imageGallery: [
      "/image/projects/alleat/slides/alleatcategoriesslide.webp",
      "/image/projects/alleat/slides/alleatconfirmedorderslide.webp",
      "/image/projects/alleat/slides/alleathomepageslide.webp",
      "/image/projects/alleat/slides/alleatitemslide.webp",
    ],
  },
  {
    title: "Kat Sullivan",
    description:
      "Kat Sullivan's blog website was developed from the ground up to be accessible for her to manage her content and constantly update it with any changes she needed to make - to facilitate this, I made use of WordPress which has a simple to use block based page building system. To design the site, I heavily used Figma in order to display mockups and get real-time feedback on how the site felt and places that they felt needed changing. Through iterations, it was found that some of the needs would not be able to be fully met by WordPress so PHP was used for some custom contact forms and subscription forms to different newsletters.",
    url: "katsullivan",
    startDate: "2020-03",
    endDate: "2020-05",
    languages: ["PHP"],
    classification: ["Work Project"],
    type: "Web Development",
    tools: ["WordPress", "Figma"],
    thumbnailImage:
      "/image/projects/katsullivan/slides/katsullivanhomepageslide.webp",
    coverImage: "/image/projects/katsullivan/katsullivanhomepage.png",
    imageGallery: [
      "/image/projects/katsullivan/slides/katsullivanaboutslide.webp",
      "/image/projects/katsullivan/slides/katsullivanblogslide.webp",
    ],
  },
  {
    title: "Passagetopoise",
    description:
      "Passagetopoise is a fashion-focused portfolio website that I designed and developed in collaboration with the client. Using Adobe XD, I created multiple design iterations based on client feedback to ensure alignment with their brand.\n\nThe final design was implemented in WordPress, enabling the client to manage and update content independently. Upon launch, site maintenance was transitioned to an external agency.\n\nThe design phase took approximately two months, followed by three months of development. In the months following release, I continued to deliver additional features, including an e-commerce integration to support online sales.",
    url: "passagetopoise",
    startDate: "2019-11",
    endDate: "2020-12",
    classification: ["Work Project"],
    type: "Web Development",
    languages: ["PHP"],
    tools: ["WordPress", "Adobe XD"],
    thumbnailImage:
      "/image/projects/passagetopoise/slides/passagetopoisehomepageslide.webp",
    coverImage: "/image/projects/passagetopoise/passagetopoisehomepage.png",
    imageGallery: [
      "/image/projects/passagetopoise/slides/passagetopoiseblogslide.webp",
      "/image/projects/passagetopoise/slides/passagetopoisedescriptionslide.webp",
      "/image/projects/passagetopoise/slides/passagetopoiseshopslide.webp",
    ],
  },
  {
    title: "CPUR",
    description:
      "CPUR is a phone repair company that I ran for four years. As the business expanded, I designed and built multiple versions of the website in order to simplify and streamline the booking process. During early versions, I initially implemented a basic form, which was later replaced with a multi-step version that could calculate repair estimates and determine what was wrong with the device in question. \n \nAlongside technical development, I worked on core business operations including building queue management systems and developing APIs that automated the process of ordering replacement parts. I also explored A/B marketing strategies, running targeted campaigns to reach customers in the local area effectively.\n \nTo provide more value and trust in the business, I maintained a blog that educated users about common problems with their devices and solutions to many of them and how to prevent many of these issues from occurring again and provided a free service to do over the phone troubleshooting help.\n \nThis project strengthened my skills in web development, automation, user experience design, marketing, customer communication, and business management, all while operating in a fast paced, client-facing environment",
    url: "cpur",
    startDate: "2019-03",
    endDate: "2022-12",
    classification: ["Work Project"],
    type: "Web Development",
    languages: ["PHP"],
    tools: ["WordPress", "Figma", "Adobe Photoshop", "Adobe Illustrator"],
    thumbnailImage: "/image/projects/cpur/slides/cpurhomepageslide.webp",
    coverImage: "/image/projects/cpur/cpurhomepage.png",
    imageGallery: [
      "/image/projects/cpur/slides/cpurdatarecoveryslide.webp",
      "/image/projects/cpur/slides/cpurgetstartedslide.webp",
      "/image/projects/cpur/slides/cpurhomepageslide.webp",
      "/image/projects/cpur/slides/cpurrepairslide.webp",
    ],
  },
  {
    title: "SSH Cart",
    description:
      "SSH Cart is a web-based collaborative cart system designed for shared households to split the cost of delivery by ordering as a single delivery while allowing each member to have their own virtual carts, ensuring that each person's order remains private and protected from interference\n\nThis project done as part of the module Software Engineering and Professional Practice at the University of Birmingham.  Through this module, we were taught about the fundamentals of GitHub and servers, learning how to generate and pitch ideas using an Engineering Design Review (EDR). After pitching our individual ideas, we formed teams of four and used the EDR framework to collaboratively design the product.\n\nAs the team lead, I was responsible for delegating tasks based on each member's strengths and managing the project's progress. I handled the frontend development for the cart system, ensuring a clean and intuitive user interface while coordinating with the rest of the team to integrate our work seamlessly. By performing it this way, each person was responsible with communicating with 2 people instead of the entire team while also allowing for mutual interaction.\n\nThroughout the project, we used our skills learnt in the lectures, to use GitHub effectively for task management and tracking issues. On top of this, our weekly meetings allowed each of us to talk about the project and aid each other in areas we were struggling at. This allowed us to get the project completed to a high standard and as a result we got a First in this module.",
    url: "sshcart",
    startDate: "2024-11-18",
    endDate: "2024-12-11",
    classification: ["University Project"],
    type: "Web Development",
    languages: ["HTML", "CSS", "JavaScript", "NodeJS"],
    tools: ["Visual Studio Code", "Docker", "MongoDB", "Figma"],
    coverImage: "/image/projects/sshcart/sshcart.png",
    thumbnailImage: "/image/projects/sshcart/slides/sshslide.webp",
    imageGallery: ["/image/placeholder.jpg"],
  },
  {
    title: "BlocDoc",
    description:
      "BlocDoc is a note-taking and study tool web application developed to enhance the student learning experience through integrated revision workflows. The project was created as part of the 2nd Year Team Project module run by the University of Birmingham and was made up of groups of 6-8 students working in an agile environment using vertical slicing and CI/CD practices.\n\nUnlike much of the other competition, it embeds the flashcards within documents, by making documents work through modular blocks, allowing for seamless transitions between reviewing cards and documents. The application contains a study page which compiles the flashcards from the documents and uses spaced repetition, encouraging long-term memory retention. Each document and flashcard, blocks can be inserted including text, tables, code, images and PDFs. Users can also export their documents into a variety formats or share them publicly.\n\nBlocDoc also includes an intelligent deadlines module to track assignments and assessments to allow users to manage their workload with colour-coded levels of priority - After a deadline is marked completed, it is placed in an archived table.",
    url: "blocdoc",
    startDate: "2025-01-19",
    endDate: "2025-05-04",
    featured: true,
    coverImage: "/image/projects/blocdoc/blocdocdocument.png",
    thumbnailImage: "/image/projects/blocdoc/slides/blocdocdocumentslide.webp",
    classification: ["University Project"],
    type: "Web Development",
    languages: ["TypeScript", "CSS", "Java"],
    tools: ["JHipster", "Docker", "Figma", "Visual Studio Code"],
    imageGallery: ["/image/placeholder.jpg"],
  },
  {
    title: "Advanced News Classifier",
    description:
      "Advanced News Classifier was a project developed as part of a first-year module at the University of Birmingham, designed to assess our understanding of the Java language using natural language processing techniques. We were provided with some base code to start us off and by using the documentation of the library for NLPs, we built a classifier that could categorise new articles by genre based solely on the articles' text content. Through feature extraction, training and evaluation of multiple models and performance tuning the final model achieved an accuracy of 85% on the test database.",
    url: "newsclassifier",
    startDate: "2023-11-27",
    endDate: "2023-12-11",
    classification: ["University Project"],
    type: "Machine Learning Development",
    languages: ["Java"],
    tools: ["IntelliJ IDEA"],
    thumbnailImage:
      "/image/projects/newsclassifier/slides/newsclassifierslide.webp",
    coverImage: "/image/projects/newsclassifier/newsclassifier.png",
    imageGallery: [""],
  },
  {
    title: "Record Shop",
    description:
      "Record Shop was a first-year assignment at the University of Birmingham, designed to test my ability to create, manage, and query databases using SQL. The project involved performing data analysis on provided datasets and writing efficient SQL statements to extract  data. To further test our skills, it additionally asked us to develop a 3-tier TCP based networking multi-threaded client-server application that is used to store data on a chain store and their vinyl records. With the use of Java, JavaFX and a database of PostgreSQL, I was able to successfully do this and get a score of 92/100.",
    url: "recordshop",
    startDate: "2024-03-14",
    endDate: "2024-05-02",
    tags: [
      "Small Project",
      "University Project",
      "Backend Development",
      "Database Development",
    ],
    languages: ["Java", "JavaFX", "PostgreSQL"],
    tools: ["IntelliJ IDEA"],
    thumbnailImage: "/image/projects/recordshop/slides/recordshopslide.webp",
    coverImage: "/image/projects/recordshop/recordshop.png",
    imageGallery: [""],
  },
  {
    title: "30 Days of UI",
    description:
      "This project is upcoming 😭. Come back later to see the full breakdown",
    url: "30daysofui",
    startDate: "2025-08",
    endDate: "2025-09",
    classification: ["Personal Project", "Challenge"],
    languages: [],
    type: "UI/UX Design",
    tools: ["Figma", "Adobe Photoshop", "Adobe Illustrator"],
    thumbnailImage: "image/projects/30daysofui/slides/30daysofuislide.webp",
    coverImage: "/image/projects/30daysofui/30daysofui.png",
    imageGallery: ["/image/placeholder.jpg"],
  },
  {
    title: "SyncMove",
    description:
      "SyncMove is a startup company that has made an app designed to help students connect with gym partners, build fitness-based friendships, and stay motivated through challenges. With a focus on wellbeing and community, SyncMove aims itself at students to find other people to workout with.\n\nDuring July and August, I worked with them for an internship, working initially as an app developer, with the responsibilities to help rebuild the application for version 2.0's release, with new features and design style. During the development of the app, I spent my free time working on an updated mockup of version 2.0 and presented it in front of the CEO, with my new ideas and thoughts on ways to improve the design for better user experience. He agreed with my plan and assigned me as lead visual designer, working on continuing my progress on the mockup and helping innovate new potential features.",
    url: "syncmove",
    startDate: "2025-07",
    endDate: "2025-08",
    featured: true,
    classification: ["Work Project"],
    tools: ["Figma", "Visual Studio Code", "Android Studio", "Postman"],
    languages: ["TypeScript", "HTML", "CSS", "JavaScript", "Java"],
    thumbnailImage: "image/projects/syncmove/slides/syncmoveslide.webp",
    coverImage: "/image/projects/syncmove/syncmovehomescreen.jpeg",
    type: "App Development & UI/UX Design",
  },
  {
    title: "Roll for Answers",
    description:
      "Roll for Answers is a podcast that I wrote, hosted, and edited for the University of Birmingham's Tabletop Gaming Society. The podcast explored a new question every two weeks, focusing on breaking down different topics into their core mechanics, history, and impact within the world of tabletop role-playing games (TTRPGs). Over the course of the series, I brought in a variety of society members and guest speakers to create engaging discussions and provide diverse perspectives on the topics covered.\n\nAs the podcast's creator, my responsibilities included researching and scripting episodes to ensure they were well-structured and informative. I also acted as the lead host, guiding conversations and asking questions to keep discussions insightful and engaging. Additionally, I coordinated with guests to prepare them for their appearances and ensure smooth episode flow.\n\nI handled the audio recording, editing, and post-production for each episode, which strengthened my skills in sound design, pacing, and polishing dialogue to deliver a professional listening experience. Alongside production, I worked on promoting the podcast within the society, encouraging community participation and fostering greater engagement among members.",
    url: "rollforanswers",
    startDate: "2025-08",
    endDate: "2026-06",
    classification: ["Personal Project"],
    type: "Podcast",
    languages: [],
    tools: ["Audacity", "RSS", "Adobe Illustrator"],
    thumbnailImage:
      "image/projects/rollforanswers/slides/rollforanswersslide.webp",
  },
  {
    title: "The Great Beyond",
    description:
      "The game The Great Beyond was run as part of the Tabletop Gaming Society at the University of Birmingham, designing and developing a game for 10 people within the society in order to promote communication and story telling. Through the course of the development of the game, I gained experience in world-building and creating branching storylines that are easy to engage with and easy to follow. I also refined my map-making and environmental design skills, enhancing the overall experience for the players.\n\nWith storytelling, I focused on maintaining pacing in order to create memorable character-driven moments that stuck with the players and with the combined development of my voice acting skills, it brought the characters narrated through the storytelling aspects, to life. With constant feedback from the players, I learned how to adapt content dynamically and on the fly, strengthening my skills in creative design, communication and audience management.",
    type: "Game Development",
    url: "thegreatbeyond",
    startDate: "2024-10",
    endDate: "2025-07",
    tools: ["Obsidian", "Adobe Illustrator", "D&D Beyond", "Roll20"],
    thumbnailImage:
      "image/projects/thegreatbeyond/slides/thegreatbeyondslide.webp",
  },
  {
    title: "Take Ctrl",
    description:
      "Take Ctrl was a mock marketing campaign I developed during a work experience program with Acer UK. The goal was to create a marketing strategy aimed at engaging younger audiences and improving Acer's outreach on social platforms. During this time, I gained hands-on experience in market research, competitor analysis, and identifying effective marketing strategies tailored to emerging trends.\n\nAt the time, Acer was preparing to launch the Acer Vero, and our team was tasked with designing a concept advertising campaign for their Instagram account. I successfully delivered a campaign proposal to a high standard, and several of my ideas were taken on board by the team to inform their future marketing direction.\n\nThroughout the work experience, I had the opportunity to engage directly with key departments across Acer UK, including marketing, finance, product design, sales, and the field operations team - This gave me valuable insights into how different areas of the business collaborate to bring products to market and strengthened my understanding of cross-departmental communication and strategic planning.",
    type: "Marketing",
    url: "takectrl",
    tools: ["Figma", "Microsoft Word"],
    startDate: "2022-07-11",
    endDate: "2022-07-15",
    thumbnailImage: "image/projects/takectrl/slides/takectrlslide.webp",
  },
];
